name = "demo"
version = "0.1.0"
defaultTargets = ["demo"]

[[lean_lib]]
name = "Demo"

[[lean_exe]]
name = "demo"
root = "Main"

[[require]]
name = "proofwidgets"
git = "https://github.com/leanprover-community/ProofWidgets4"
rev = "bb700f4"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.18.0"
